version: '3'

services:
  slinkyfrontend:
    build:
      context: ../src/SlinkyFrontEnd
    image: 'lwg/slinkyux:dev'
    hostname: 'slinkyfrontend'
    restart: always
    expose:
      - 3000
    networks:
      - slinkynet

  slinky:
    build:
      context: ../src/SlinkyApiServer
    image: 'lwg/slinky:dev'
    hostname: 'slinkyapi_node1'
    restart: always
    volumes:
      - ../config/slinky.conf:/app/appsettings.json:ro
    expose:
      - 5000
    networks:
      - slinkynet
 
  nginx:
    image: 'nginx:1.21.6-alpine'
    hostname: 'nginx'
    restart: always
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - slinky
      - slinkyfrontend
    networks:
      - slinkynet

networks:
  slinkynet:
    driver: bridge
