version: '3'

services:

  slinky:
    build:
      context: ../src/
    image: 'lwg/slinky:latest'
    hostname: 'slinkyapi_node1'
    restart: always
    volumes:
      - ../config/slinky.node1.conf:/app/appsettings.json:ro
    expose:
      - 5000
    networks:
      - slinkynet
 
  nginx:
    image: 'nginx:1.21.6-alpine'
    hostname: 'nginx'
    restart: always
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../src/slinky/slinky.ux/build/:/usr/share/nginx/html/slinky/:ro
    ports:
      - 443:443
    depends_on:
      - slinky
    networks:
      - slinkynet
networks:
  slinkynet:
    driver: bridge
